<div id="<?= $this->widget->messageType; ?>">
    <div class="message">
      <p><?= $this->widget->text; ?></p>
    </div>
    <? if ($this->widget->links): ?>
    <div class="action">
        <div id="messageBarWrap">
            <div id="messageBar" class="center">
                <? foreach ($this->widget->links as $link): ?>
                <a id="<?= $link->title; ?>-24" class="Tips button" href="<?= $link->url ?>" title="<?= ucfirst($link->title); ?>" rel="<?= $link->rel; ?>">
                    <span><?= ucfirst($link->title); ?></span>
                </a>
                <? endforeach; ?>
              <div class="both"></div>
            </div>
        </div>
    </div>
    <? endif; ?>
</div>