<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 30 Jul 2009 17:29 18
[css]
0 = "/templates/abstractportal/css/template.css"
[js_ini_files]
0 = "/templates/abstractportal/js/UthandoAPI.js"
1 = "/templates/abstractportal/js/UthandoConfig.js"
[mootools_js]
0 = "/Common/javascript/Source/Core/Core.js"
1 = "/Common/javascript/Source/Core/Browser.js"
2 = "/Common/javascript/Source/Native/Array.js"
3 = "/Common/javascript/Source/Native/Function.js"
4 = "/Common/javascript/Source/Native/Number.js"
5 = "/Common/javascript/Source/Native/String.js"
6 = "/Common/javascript/Source/Native/Hash.js"
7 = "/Common/javascript/Source/Native/Event.js"
8 = "/Common/javascript/Source/Class/Class.js"
9 = "/Common/javascript/Source/Class/Class.Extras.js"
10 = "/Common/javascript/Source/Element/Element.js"
11 = "/Common/javascript/Source/Element/Element.Event.js"
12 = "/Common/javascript/Source/Element/Element.Style.js"
13 = "/Common/javascript/Source/Element/Element.Dimensions.js"
14 = "/Common/javascript/Source/Utilities/Selectors.js"
15 = "/Common/javascript/Source/Utilities/DomReady.js"
16 = "/Common/javascript/Source/Utilities/Swiff.js"
17 = "/Common/javascript/Source/Fx/Fx.js"
18 = "/Common/javascript/Source/Fx/Fx.CSS.js"
19 = "/Common/javascript/Source/Fx/Fx.Tween.js"
20 = "/Common/javascript/Source/Fx/Fx.Morph.js"
21 = "/Common/javascript/Source/Request/Request.js"
22 = "/Common/javascript/Source/Request/Request.HTML.js"
23 = "/Common/javascript/Source/Core/More.js"
24 = "/Common/javascript/Source/Class/Class.Refactor.js"
25 = "/Common/javascript/Source/Class/Class.Binds.js"
26 = "/Common/javascript/Source/Class/Class.Occlude.js"
27 = "/Common/javascript/Source/Native/URI.js"
28 = "/Common/javascript/Source/Element/Element.Measure.js"
29 = "/Common/javascript/Source/Element/Element.Position.js"
30 = "/Common/javascript/Source/Element/Element.Shortcuts.js"
31 = "/Common/javascript/Source/Fx/Fx.Elements.js"
32 = "/Common/javascript/Source/Fx/Fx.Accordion.js"
33 = "/Common/javascript/Source/Fx/Fx.Scroll.js"
34 = "/Common/javascript/Source/Drag/Drag.js"
35 = "/Common/javascript/Source/Drag/Slider.js"
36 = "/Common/javascript/Source/Utilities/Assets.js"
37 = "/Common/javascript/Source/Utilities/IframeShim.js"
38 = "/Common/javascript/Source/Interface/Tips.js"
39 = "/Common/javascript/Source/Core/Clientcide.js"
40 = "/Common/javascript/Source/Core/dbug.js"
41 = "/Common/javascript/Source/Browser/FixPNG.js"
42 = "/Common/javascript/Source/UI/Waiter.js"
43 = "/Common/javascript/Source/Browser/HistoryManager.js"
44 = "/Common/javascript/Source/Layout/ajaxLinks.js"
45 = "/Common/javascript/Source/Layout/Pagination.js"
[Core]
0 = "Core"
1 = "Browser"
2 = "More"
3 = "Clientcide"
4 = "dbug"
[Native]
0 = "Array"
1 = "Function"
2 = "Number"
3 = "String"
4 = "Hash"
5 = "Event"
6 = "URI"
[Class]
0 = "Class"
1 = "Class.Extras"
2 = "Class.Refactor"
3 = "Class.Binds"
4 = "Class.Occlude"
[Element]
0 = "Element"
1 = "Element.Event"
2 = "Element.Style"
3 = "Element.Dimensions"
4 = "Element.Measure"
5 = "Element.Position"
6 = "Element.Shortcuts"
[Utilities]
0 = "Selectors"
1 = "DomReady"
2 = "Swiff"
3 = "Assets"
4 = "IframeShim"
[Fx]
0 = "Fx"
1 = "Fx.CSS"
2 = "Fx.Tween"
3 = "Fx.Morph"
4 = "Fx.Elements"
5 = "Fx.Accordion"
6 = "Fx.Scroll"
[Request]
0 = "Request"
1 = "Request.HTML"
[Drag]
0 = "Drag"
1 = "Slider"
[Interface]
0 = "Tips"
[Browser]
0 = "FixPNG"
1 = "HistoryManager"
[UI]
0 = "Waiter"
[Layout]
0 = "ajaxLinks"
1 = "Pagination"

; -- END PROTECTED_MODE
; */
?>
