/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of IP.xs. Do not edit this file, edit IP.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "IP.xs"
#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "GeoIP.h"
#include "GeoIPCity.h"

#ifdef __cplusplus
}
#endif

#line 26 "IP.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 69 "IP.c"

XS(XS_Geo__IP_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "CLASS, flags = 0");
    {
	char *	CLASS;
	int	flags;
	GeoIP *	RETVAL;

    if( SvOK(ST(0)) )
       CLASS = (char *) SvPV(ST(0), PL_na);
    else {
       CLASS = NULL;
    };

	if (items < 2)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(1));
	}
#line 25 "IP.xs"
	RETVAL = GeoIP_new(flags);
#line 99 "IP.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), (char *)CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Geo__IP_open_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_open_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "CLASS, type, flags = 0");
    {
	char *	CLASS;
	int	type = (int)SvIV(ST(1));
	int	flags;
	GeoIP *	RETVAL;

    if( SvOK(ST(0)) )
       CLASS = (char *) SvPV(ST(0), PL_na);
    else {
       CLASS = NULL;
    };

	if (items < 3)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(2));
	}
#line 35 "IP.xs"
	RETVAL = GeoIP_open_type(type,flags);
#line 137 "IP.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), (char *)CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Geo__IP_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "CLASS, filename, flags = 0");
    {
	char *	CLASS;
	char *	filename;
	int	flags;
	GeoIP *	RETVAL;

    if( SvOK(ST(0)) )
       CLASS = (char *) SvPV(ST(0), PL_na);
    else {
       CLASS = NULL;
    };

    if( SvOK(ST(1)) )
       filename = (char *) SvPV(ST(1), PL_na);
    else {
       filename = NULL;
    };

	if (items < 3)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(2));
	}
#line 45 "IP.xs"
	RETVAL = ( filename != NULL ) ? GeoIP_open(filename,flags) : NULL;
#line 181 "IP.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), (char *)CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Geo__IP_id_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_id_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::id_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 54 "IP.xs"
	RETVAL = GeoIP_id_by_addr(gi,addr);
#line 220 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_id_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_id_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    {
	GeoIP *	gi;
	char *	name;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::id_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 63 "IP.xs"
	RETVAL = GeoIP_id_by_name(gi,name);
#line 257 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_database_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_database_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gi");
    {
	GeoIP *	gi;
	char *	RETVAL;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::database_info() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 71 "IP.xs"
	RETVAL = GeoIP_database_info(gi);
#line 286 "IP.c"
	ST(0) = sv_newmortal();
    if(RETVAL != NULL) {
        ST(0) = newSVpv(RETVAL, strlen(RETVAL));
        free(RETVAL);
        sv_2mortal(ST(0));
    }
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_code_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_code_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_code_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 80 "IP.xs"
	RETVAL = GeoIP_country_code_by_addr(gi,addr);
#line 328 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_code_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_code_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    {
	GeoIP *	gi;
	char *	name;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_code_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 89 "IP.xs"
	RETVAL = GeoIP_country_code_by_name(gi,name);
#line 365 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_code3_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_code3_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_code3_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 98 "IP.xs"
	RETVAL = GeoIP_country_code3_by_addr(gi,addr);
#line 402 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_code3_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_code3_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    {
	GeoIP *	gi;
	char *	name;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_code3_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 107 "IP.xs"
	RETVAL = GeoIP_country_code3_by_name(gi,name);
#line 439 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_name_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_name_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_name_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 116 "IP.xs"
	RETVAL = GeoIP_country_name_by_addr(gi,addr);
#line 476 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_country_name_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_country_name_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    {
	GeoIP *	gi;
	char *	name;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::country_name_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 125 "IP.xs"
	RETVAL = GeoIP_country_name_by_name(gi,name);
#line 513 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_org_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_org_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
	char *	RETVAL;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::org_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 134 "IP.xs"
	RETVAL = GeoIP_org_by_addr(gi,addr);
#line 549 "IP.c"
	ST(0) = sv_newmortal();
    if(RETVAL != NULL) {
        ST(0) = newSVpv(RETVAL, strlen(RETVAL));
        free(RETVAL);
        sv_2mortal(ST(0));
    }
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_org_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_org_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    {
	GeoIP *	gi;
	char *	name;
	char *	RETVAL;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::org_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 143 "IP.xs"
	RETVAL = GeoIP_org_by_name(gi,name);
#line 590 "IP.c"
	ST(0) = sv_newmortal();
    if(RETVAL != NULL) {
        ST(0) = newSVpv(RETVAL, strlen(RETVAL));
        free(RETVAL);
        sv_2mortal(ST(0));
    }
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_range_by_ip); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_range_by_ip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	GeoIP *	gi;
	const char *	addr = (const char *)SvPV_nolen(ST(1));
#line 152 "IP.xs"
    char ** r;
#line 619 "IP.c"

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::range_by_ip() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 154 "IP.xs"
	r = GeoIP_range_by_ip(gi,addr);
        if (r != NULL){
		EXTEND(SP,2);
		PUSHs( sv_2mortal( newSVpv(r[0], 0) ) );
		PUSHs( sv_2mortal( newSVpv(r[1], 0) ) );

		if ( r[0] )
			free(r[0]);
		if ( r[1] )
			free(r[1]);
		free(r);
        }
#line 640 "IP.c"
	PUTBACK;
	return;
    }
}


XS(XS_Geo__IP_region_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_region_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	GeoIP *	gi;
	char *	addr;
#line 172 "IP.xs"
	GeoIPRegion * gir;
#line 664 "IP.c"

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::region_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 174 "IP.xs"
	gir = GeoIP_region_by_addr(gi,addr);
        if (gir){
	  EXTEND(SP,2);

          ( gir->country_code[0] == '\0' && gir->country_code[1] == '\0' )
            ? PUSHs ( sv_newmortal() )
 	    : PUSHs ( sv_2mortal( newSVpv(gir->country_code, 2) ) );

          ( gir->region[0] == '\0' && gir->region[1] == '\0' )
            ? PUSHs ( sv_newmortal() )
            : PUSHs( sv_2mortal( newSVpv(gir->region, 2) ) );

          GeoIPRegion_delete(gir);
        }
#line 693 "IP.c"
	PUTBACK;
	return;
    }
}


XS(XS_Geo__IP_region_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_region_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, name");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	GeoIP *	gi;
	char *	name;
#line 194 "IP.xs"
	GeoIPRegion * gir;
#line 717 "IP.c"

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::region_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       name = (char *) SvPV(ST(1), PL_na);
    else {
       name = NULL;
    };
#line 196 "IP.xs"
	gir = GeoIP_region_by_name(gi,name);
        if (gir){
	  EXTEND(SP,2);

          ( gir->country_code[0] == '\0' && gir->country_code[1] == '\0' )
            ? PUSHs ( sv_newmortal() )
 	    : PUSHs ( sv_2mortal( newSVpv(gir->country_code, 2) ) );

          ( gir->region[0] == '\0' && gir->region[1] == '\0' )
            ? PUSHs ( sv_newmortal() )
            : PUSHs( sv_2mortal( newSVpv(gir->region, 2) ) );

	  GeoIPRegion_delete(gir);
        }
#line 746 "IP.c"
	PUTBACK;
	return;
    }
}


XS(XS_Geo__IP_record_by_addr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_record_by_addr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
#line 216 "IP.xs"
	char * CLASS = "Geo::IP::Record";
#line 768 "IP.c"
	GeoIPRecord *	RETVAL;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::record_by_addr() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 218 "IP.xs"
	RETVAL = GeoIP_record_by_addr(gi,addr);
#line 785 "IP.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), (char *)CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Geo__IP_record_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_record_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, addr");
    {
	GeoIP *	gi;
	char *	addr;
#line 227 "IP.xs"
	char * CLASS = "Geo::IP::Record";
#line 809 "IP.c"
	GeoIPRecord *	RETVAL;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::record_by_name() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };

    if( SvOK(ST(1)) )
       addr = (char *) SvPV(ST(1), PL_na);
    else {
       addr = NULL;
    };
#line 229 "IP.xs"
	RETVAL = GeoIP_record_by_name(gi,addr);
#line 826 "IP.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), (char *)CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Geo__IP_set_charset); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_set_charset)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gi, charset");
    {
	GeoIP *	gi;
	int	charset = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::set_charset() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 238 "IP.xs"
	RETVAL = GeoIP_set_charset(gi, charset);
#line 859 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_charset); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_charset)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gi");
    {
	GeoIP *	gi;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::charset() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 246 "IP.xs"
	RETVAL = GeoIP_charset(gi);
#line 889 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_last_netmask); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_last_netmask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gi");
    {
	GeoIP *	gi;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::last_netmask() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 254 "IP.xs"
	RETVAL = GeoIP_last_netmask(gi);
#line 919 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gi");
    {
	GeoIP *	gi;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gi = (GeoIP *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::DESTROY() -- gi is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 262 "IP.xs"
	GeoIP_delete(gi);
#line 947 "IP.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Geo__IP__Record_country_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_country_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::country_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 270 "IP.xs"
	RETVAL = (const char *)gir->country_code;
#line 976 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_country_code3); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_country_code3)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::country_code3() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 278 "IP.xs"
	RETVAL = (const char *)gir->country_code3;
#line 1006 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_country_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_country_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::country_name() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 286 "IP.xs"
	RETVAL = (const char *)gir->country_name;
#line 1036 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_region); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_region)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::region() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 294 "IP.xs"
	RETVAL = (const char *)gir->region;
#line 1066 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_region_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_region_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::region_name() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 302 "IP.xs"
	RETVAL = (const char *) GeoIP_region_name_by_code(gir->country_code, gir->region);
#line 1096 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_time_zone); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_time_zone)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::time_zone() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 310 "IP.xs"
	RETVAL = (const char *) GeoIP_time_zone_by_country_and_region(gir->country_code, gir->region);
#line 1126 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_city); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_city)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	GeoIPRecord *	gir;
#line 318 "IP.xs"
        SV * n;
#line 1149 "IP.c"

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::city() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 320 "IP.xs"
        n = newSVpv( gir->city ? gir->city : "", 0);
#if defined(sv_utf8_decode)
        if ( gir->charset == GEOIP_CHARSET_UTF8 )
          SvUTF8_on(n);
#endif
        sv_2mortal(n);
        ST(0) = n;
        XSRETURN(1);
#line 1166 "IP.c"
	PUTBACK;
	return;
    }
}


XS(XS_Geo__IP__Record_postal_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_postal_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::postal_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 333 "IP.xs"
	RETVAL = (const char *)gir->postal_code;
#line 1196 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record__latitude); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record__latitude)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	float	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::_latitude() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 341 "IP.xs"
	RETVAL = gir->latitude;
#line 1226 "IP.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record__longitude); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record__longitude)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	float	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::_longitude() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 349 "IP.xs"
	RETVAL = gir->longitude;
#line 1256 "IP.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_dma_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_dma_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::dma_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 357 "IP.xs"
	RETVAL = gir->dma_code;

#line 1287 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_metro_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_metro_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::metro_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 366 "IP.xs"
       RETVAL = gir->dma_code; /* we can NOT use metro_code here. metro_code may be not present in older CAPI's */
#line 1317 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_area_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_area_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	int	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::area_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 374 "IP.xs"
	RETVAL = gir->area_code;
#line 1347 "IP.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_continent_code); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_continent_code)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;
	const char *	RETVAL;
	dXSTARG;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::continent_code() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 382 "IP.xs"
	RETVAL = (const char *)gir->continent_code;
#line 1377 "IP.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Geo__IP__Record_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "gir");
    {
	GeoIPRecord *	gir;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
            gir = (GeoIPRecord *)SvIV((SV*)SvRV( ST(0) ));
    else{
            warn( "Geo::IP::Record::DESTROY() -- gir is not a blessed SV reference" );
            XSRETURN_UNDEF;
    };
#line 390 "IP.xs"
	GeoIPRecord_delete(gir);
#line 1405 "IP.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Geo__IP__Record__XScompiled); /* prototype to pass -Wmissing-prototypes */
XS(XS_Geo__IP__Record__XScompiled)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 395 "IP.xs"
	XSRETURN_YES;
#line 1424 "IP.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Geo__IP); /* prototype to pass -Wmissing-prototypes */
XS(boot_Geo__IP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Geo::IP::new", XS_Geo__IP_new, file);
        newXS("Geo::IP::open_type", XS_Geo__IP_open_type, file);
        newXS("Geo::IP::open", XS_Geo__IP_open, file);
        newXS("Geo::IP::id_by_addr", XS_Geo__IP_id_by_addr, file);
        newXS("Geo::IP::id_by_name", XS_Geo__IP_id_by_name, file);
        newXS("Geo::IP::database_info", XS_Geo__IP_database_info, file);
        newXS("Geo::IP::country_code_by_addr", XS_Geo__IP_country_code_by_addr, file);
        newXS("Geo::IP::country_code_by_name", XS_Geo__IP_country_code_by_name, file);
        newXS("Geo::IP::country_code3_by_addr", XS_Geo__IP_country_code3_by_addr, file);
        newXS("Geo::IP::country_code3_by_name", XS_Geo__IP_country_code3_by_name, file);
        newXS("Geo::IP::country_name_by_addr", XS_Geo__IP_country_name_by_addr, file);
        newXS("Geo::IP::country_name_by_name", XS_Geo__IP_country_name_by_name, file);
        newXS("Geo::IP::org_by_addr", XS_Geo__IP_org_by_addr, file);
        newXS("Geo::IP::org_by_name", XS_Geo__IP_org_by_name, file);
        newXS("Geo::IP::range_by_ip", XS_Geo__IP_range_by_ip, file);
        newXS("Geo::IP::region_by_addr", XS_Geo__IP_region_by_addr, file);
        newXS("Geo::IP::region_by_name", XS_Geo__IP_region_by_name, file);
        newXS("Geo::IP::record_by_addr", XS_Geo__IP_record_by_addr, file);
        newXS("Geo::IP::record_by_name", XS_Geo__IP_record_by_name, file);
        newXS("Geo::IP::set_charset", XS_Geo__IP_set_charset, file);
        newXS("Geo::IP::charset", XS_Geo__IP_charset, file);
        newXS("Geo::IP::last_netmask", XS_Geo__IP_last_netmask, file);
        newXS("Geo::IP::DESTROY", XS_Geo__IP_DESTROY, file);
        newXS("Geo::IP::Record::country_code", XS_Geo__IP__Record_country_code, file);
        newXS("Geo::IP::Record::country_code3", XS_Geo__IP__Record_country_code3, file);
        newXS("Geo::IP::Record::country_name", XS_Geo__IP__Record_country_name, file);
        newXS("Geo::IP::Record::region", XS_Geo__IP__Record_region, file);
        newXS("Geo::IP::Record::region_name", XS_Geo__IP__Record_region_name, file);
        newXS("Geo::IP::Record::time_zone", XS_Geo__IP__Record_time_zone, file);
        newXS("Geo::IP::Record::city", XS_Geo__IP__Record_city, file);
        newXS("Geo::IP::Record::postal_code", XS_Geo__IP__Record_postal_code, file);
        newXS("Geo::IP::Record::_latitude", XS_Geo__IP__Record__latitude, file);
        newXS("Geo::IP::Record::_longitude", XS_Geo__IP__Record__longitude, file);
        newXS("Geo::IP::Record::dma_code", XS_Geo__IP__Record_dma_code, file);
        newXS("Geo::IP::Record::metro_code", XS_Geo__IP__Record_metro_code, file);
        newXS("Geo::IP::Record::area_code", XS_Geo__IP__Record_area_code, file);
        newXS("Geo::IP::Record::continent_code", XS_Geo__IP__Record_continent_code, file);
        newXS("Geo::IP::Record::DESTROY", XS_Geo__IP__Record_DESTROY, file);
        newXS("Geo::IP::Record::_XScompiled", XS_Geo__IP__Record__XScompiled, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

