<?php
; /*
; -- BEGIN PROTECTED_MODE
; This file was automatically generated by Config
; Do not edit this file by hand, use Config instead.
; Last modified: 04 Dec 2009 10:30 19
[general]
name = "setup"
custom = 0
compress_files = "0"
xmlprolog = 0
doctype = "XHTML 1.0 Strict"
cache = 0
dbug = 1
[cache]
[css]
0 = "/setup/template/css/style.css"
[js]
0 = "/setup/template/js/mootools-1.2.4-core-yc.js"
1 = "/setup/template/js/mootools-1.2.4.4-more.js"
2 = "/setup/template/js/UthandoSetupAPI.js"
[mootools]


; -- END PROTECTED_MODE
; */
?>
