<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 11 Jan 2007 15:44 52
[CAPTCHA]
tempfolder = "/Common/tmp/"
TTF_folder =  "/Common/TTF/"
TTF_RANGE = "auto"
chars = 6
minsize = 20
maxsize = 30
maxrotation = 25
use_only_md5 = 0
noise = 1
websafecolors = 0
refreshlink = 1
lang = "en"
maxtry = 3
badguys_url = "/"
secretstring = "A very, very secret string which is used to generate a md5-key!"
secretposition = 9
counter_filename =  "/Common/tmp/hn_captcha_counter.txt"
prefix = "hn_captcha_"
collect_garbage_after = 20
maxlifetime	= 60
debug = 0

; -- END PROTECTED_MODE
; */
?>
