<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 11 Jan 2007 15:44 52
[cipher]
key = "A secret string to be change to whatever you like."
[login]
captcha_status = "off"
[register]
captcha_status = "off"
[reminder]
captcha_status = "off"


; -- END PROTECTED_MODE
; */
?>
