<?= $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <?= $this->headMeta(); ?>

        <?= $this->headTitle(); ?>

        <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />

        <style>
            body {
                text-align: center;
            }

			img {
				border: 0px;
				vertical-align: middle;
			}
		</style>
    </head>
    <body>
        <div>
            <img src="/images/uthandocms.png" />
		</div>
        <div>
            <h2>Welcome to Uthando-CMS</h2>
            <h2>Content Management made easy.</h2>
            <h3><?= $_SERVER['SERVER_NAME']; ?> coming soon</h3>
            <p>This site is unconfigured.</p>
            <p>To configure it please go to ths control panel in the admin section</p>
        </div>
    </body>
</html>