<div id="error">
    <p class="message">
        <?= $this->message; ?>
    </p>
</div>

<?php if (isset($this->exception)): ?>
<div class="debug_message">
    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?= $this->exception->getMessage(); ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?= $this->exception->getTraceAsString(); ?></pre>

    <h3>Request Parameters:</h3>
    <pre><?= var_export($this->request->getParams(), true); ?></pre>
</div>
<?php endif ?>