<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 17 Feb 2009 03:55 09
[css]
0 = "/setup/template/css/style.css"
[js_ini_files]
0 = "/setup/template/js/UthandoSetupAPI.js"
[Utilities]
0 = "Selectors"
1 = "DomReady"
[Fx]
0 = "Fx.Tween"
1 = "Fx.SmoothAnchors"
[Request]
0 = "Request.HTML"

; -- END PROTECTED_MODE
; */
?>