<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 17 Feb 2009 03:55 09
[router]
url_type = "sef"
url_request = "content"
[urls]

; -- END PROTECTED_MODE
; */
?>
