<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 17 Feb 2009 03:55 09
[ftp]
port = "21"
host = "localhost"
username = "uthando"
password = "password"
timeout = "90"
public_html = "/htdocs/Uthando-CMS/public_html"
uthando_dir = "/htdocs/Uthando-CMS/uthando"

; -- END PROTECTED_MODE
; */
?>
