<?PHP
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 11 Jan 2007 15:44 52
[mailer]
type = "smtp"
email = "user@uthandocms.co.uk"
[mail]
[sendmail]
sendmail_path = "/usr/bin/sendmail"
sendmail_args = "-i"
[smtp]
host = "mail.uthandocms.co.uk"
port = 25
auth = "PLAIN"
username = "user@uthandocms.co.uk"
password = "password"

; -- END PROTECTED_MODE
; */
?>
