<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 13 Nov 2009 09:41 31
[paypal]
pp_merchant_id = "user@uthandocms.co.uk"
pp_currency = "GBP"
pp_ipn = "1"
pp_auto_return = "1"
pp_cancel_return = "1"
pp_merchant_logo = ""
[frontend_display]
product = "9"
product_list = "3"
category = "3"
[admin_display]
customers = "50"
product = "50"
authors = "10"
category = "10"
group = "10"
zone = "10"
country = "10"
post_level = "10"
post_cost = "10"
tax_code = "10"
tax_rate = "10"
[store]
address1 = "blah"
address2 = "blah"
city = "blah"
county = "blah"
postcode = "wd34 5gt"
country = "uk"
[contact]
title = ""
foremane = ""
surname = ""
phone = "01234 123456"
mobile = ""
fax = ""
email = "example@somewhere.com"
[checkout]
orders_email = "user@uthandocms.co.uk"
post_state = "1"
stock_control = "1"
vat_state = "0"
vat_number = ""
pay_cheque = "1"
pay_credit_card = "1"
pay_phone = "1"
pay_paypal = "1"
[attributes]
authors = "1"
isbn = "0"
[global]
offline = "0"
catelogue_mode = ""
[database_joins]
product_view = "authors"
[database_selects]
product_view = "product_id,category_id,category,name,CONCAT(forename, ' ', surname) AS author,short_description,description,isbn,price,image,image_status"

; -- END PROTECTED_MODE
; */
?>
