<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 17 Feb 2009 03:55 09
[database]
hostspec = "localhost"
admin = "uthando_admin"
username = "uthando_admin"
password = "password"
phptype = "mysql"
[server]
dbug = "1"
admin_url = "http://admin.uthandocms"
[site]
template = "admin"
default_page = "admin/overview"

; -- END PROTECTED_MODE
; */
?>
