<?php
; /*
; -- BEGIN PROTECTED_MODE
; This file was automatically generated by Config
; Do not edit this file by hand, use Config instead.
; Last modified: 08 Dec 2009 02:52 02
[database]
hostspec = "localhost"
core = "uthando_core"
user = "uthando_users"
session = "uthando_sessions"
phptype = "mysql"
[database_user]
username = "uthando_user"
password = "password"
[database_guest]
username = "uthando_guest"
password = "password"
[server]
site_name = "Shaun Freeman"
web_url = "http://uthandocms"
ssl_url = "https://uthandocms"
timezone = "Europe/London"
enable_ssl = "1"
dbug = "1"
compat_router = "0"
[site]
template = "modernviewblue"
default_page = "article/page-Welcome"

; -- END PROTECTED_MODE
; */
?>
