<?= $this->message(array(
    'text'          => 'Are you sure you would like to delete this user?',
    'type'   => 'warning',
    'links'         => array(
        array(
            'title' => 'cancel',
            'rel'   => 'Cancel and return to user list.',
            'url'   => $this->url(
                array(
                    'controller'    => 'user',
                    'action'        => 'list'
                ), 'admin', true)
        ),
        array(
            'title' => 'delete',
            'rel'   => 'Delete this user.',
            'url'   => $this->url(array(
                    'controller'    => 'user',
                    'action'        => 'delete',
                    'id'            => $this->userId,
                    'userDelete'    => true
                ), 'admin', true)
        )
    )
)); ?>