<div id="warning">
    <div class="message">
      <p>Are you sure you would like to delete this user?</p>
    </div>
    <div class="action">
        <div id="messageBarWrap">
            <div id="messageBar" class="center">
                <a id="cancel-24" class="Tips button" href="<?= $this->url(array(
                    'controller'    => 'user',
                    'action'        => 'list'
                ), 'admin', true) ?>" title="Cancel" rel="Cancel and return to user list.">
                    <span>Cancel</span>
                </a>
                <a id="delete-24" class="Tips button" href="<?= $this->url(array(
                    'controller'    => 'user',
                    'action'        => 'delete',
                    'id'            => $this->userId,
                    'userDelete'    => true
                ), 'admin', true) ?>" rel="Delete this user.">
                    <span>Delete</span>
                </a>
              <div class="both"></div>
            </div>
        </div>
    </div>
</div>