<?= $this->message(array(
    'text'  => 'User has been deleted.',
    'type'  => 'pass',
    'links' => array(
        array(
            'title' => 'back',
            'rel'   => 'Return to user list.',
            'url'   => $this->url(
                array(
                    'controller'    => 'user',
                    'action'        => 'list'
                ), 'admin', true)
        )
    )
)); ?>