<div id="menuToolbarWrap">
<!--<img width="8" height="53" id="scrollLeft" alt="scroll left" src="/images/left_scroll.png" />-->
<div id="menuToolbar">

  <ul id="iconMenuStrip">
    <li>
      <a id="new_user-24" class="Tips button iconImgs" href="<?= $this->url(array(
        'module'    => 'core',
        'controller'    => 'user',
        'action'        => 'new'
    ), 'admin', true) ?>" title="New User" rel="Create a new user.">
        <span class="iconCaptions">New User</span>
      </a>
    </li>
  </ul>
  <div class="both"></div>

</div>
<!--<img width="8" height="53" id="scrollRight" alt="scroll right" src="/images/right_scroll.png" />-->
</div>

<h2>Current Users</h2>
<table class="datatable">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->users as $user): ?>
        <tr>
            <td><?= $this->escape($user->fullname); ?></td>
            <td><?= $this->escape($user->email); ?></td>
            <td><?= $this->escape($user->role); ?></td>
            <td>
                <?php if ($this->AuthInfo('upid') <= $user->upid): ?>
                <a href="<?= $this->url(array(
                    'controller'    => 'user',
                    'action'        => 'edit',
                    'id'            => $user->userId
                ), 'admin', true); ?>"><img src="/images/24x24/Edit3.png" class="Tips" title="Edit User" rel="Click to edit the user" /></a>
                <?php else: ?>
                <img src="/images/24x24/GreyEdit3.png" class="Tips" title="Edit User" rel="You cannot edit this user" />
                <?php endif; ?>
            </td>
            <td>
                <?php if ($this->AuthInfo('upid') <= $user->upid): ?>
                <a href="<?= $this->url(array(
                    'controller'    => 'user',
                    'action'        => 'delete',
                    'id'            => $user->userId
                ), 'admin', true); ?>"><img src="/images/24x24/DeleteRed.png" class="Tips" title="Delete User" rel="Click to delete the user" /></a>
                <?php else: ?>
                <img src="/images/24x24/GreyDeleteRed.png" class="Tips" title="Delete User" rel="You cannot delete this user." />
                <?php endif; ?>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>