<?php
; /*
; -- BEGIN PROTECTED_MODE
; This file was automatically generated by Config
; Do not edit this file by hand, use Config instead.
; Last modified: 04 Dec 2009 10:30 19
[general]
name = "admin"
custom = 0
compress_files = "0"
xmlprolog = 0
doctype = "XHTML 1.0 Strict"
cache = 0
dbug = 1
[cache]
js = "/templates/admin/js/UthandoJsCache.js"
css = "/templates/admin/css/UthandoCSSCache.css"
[css]
0 = "/templates/admin/css/style.css"
[js]
0 = "/templates/admin/js/UthandoAdminAPI.js"
1 = "/templates/admin/js/UthandoAdminConfig.js"
[mootools]
0 = "/Common/javascript/Source/mootools-core/Core/Core.js"
1 = "/Common/javascript/Source/mootools-core/Core/Browser.js"
2 = "/Common/javascript/Source/mootools-core/Native/Array.js"
3 = "/Common/javascript/Source/mootools-core/Native/Function.js"
4 = "/Common/javascript/Source/mootools-core/Native/Number.js"
5 = "/Common/javascript/Source/mootools-core/Native/String.js"
6 = "/Common/javascript/Source/mootools-core/Native/Hash.js"
7 = "/Common/javascript/Source/mootools-core/Native/Event.js"
8 = "/Common/javascript/Source/mootools-core/Class/Class.js"
9 = "/Common/javascript/Source/mootools-core/Class/Class.Extras.js"
10 = "/Common/javascript/Source/mootools-core/Element/Element.js"
11 = "/Common/javascript/Source/mootools-core/Element/Element.Event.js"
12 = "/Common/javascript/Source/mootools-core/Element/Element.Style.js"
13 = "/Common/javascript/Source/mootools-core/Element/Element.Dimensions.js"
14 = "/Common/javascript/Source/mootools-core/Utilities/Selectors.js"
15 = "/Common/javascript/Source/mootools-core/Utilities/DomReady.js"
16 = "/Common/javascript/Source/mootools-core/Utilities/JSON.js"
17 = "/Common/javascript/Source/mootools-core/Utilities/Cookie.js"
18 = "/Common/javascript/Source/mootools-core/Utilities/Swiff.js"
19 = "/Common/javascript/Source/mootools-core/Fx/Fx.js"
20 = "/Common/javascript/Source/mootools-core/Fx/Fx.CSS.js"
21 = "/Common/javascript/Source/mootools-core/Fx/Fx.Tween.js"
22 = "/Common/javascript/Source/mootools-core/Fx/Fx.Morph.js"
23 = "/Common/javascript/Source/mootools-core/Fx/Fx.Transitions.js"
24 = "/Common/javascript/Source/mootools-core/Request/Request.js"
25 = "/Common/javascript/Source/mootools-core/Request/Request.HTML.js"
26 = "/Common/javascript/Source/mootools-core/Request/Request.JSON.js"
27 = "/Common/javascript/Source/mootools-more/Core/More.js"
28 = "/Common/javascript/Source/mootools-more/Class/Class.Refactor.js"
29 = "/Common/javascript/Source/mootools-more/Class/Class.Binds.js"
30 = "/Common/javascript/Source/mootools-more/Class/Class.Occlude.js"
31 = "/Common/javascript/Source/mootools-more/Native/Hash.Extras.js"
32 = "/Common/javascript/Source/mootools-more/Native/String.QueryString.js"
33 = "/Common/javascript/Source/mootools-more/Native/URI.js"
34 = "/Common/javascript/Source/mootools-more/Element/Element.Measure.js"
35 = "/Common/javascript/Source/mootools-more/Element/Element.Pin.js"
36 = "/Common/javascript/Source/mootools-more/Element/Element.Position.js"
37 = "/Common/javascript/Source/mootools-more/Element/Element.Shortcuts.js"
38 = "/Common/javascript/Source/mootools-more/Fx/Fx.Elements.js"
39 = "/Common/javascript/Source/mootools-more/Drag/Drag.js"
40 = "/Common/javascript/Source/mootools-more/Drag/Drag.Move.js"
41 = "/Common/javascript/Source/mootools-more/Drag/Slider.js"
42 = "/Common/javascript/Source/mootools-more/Utilities/Assets.js"
43 = "/Common/javascript/Source/mootools-more/Utilities/Hash.Cookie.js"
44 = "/Common/javascript/Source/mootools-more/Utilities/IframeShim.js"
45 = "/Common/javascript/Source/mootools-more/Interface/Mask.js"
46 = "/Common/javascript/Source/mootools-more/Interface/Tips.js"
47 = "/Common/javascript/Source/clientcide/Core/Clientcide.js"
48 = "/Common/javascript/Source/clientcide/Core/dbug.js"
49 = "/Common/javascript/Source/clientcide/Class/Class.ToElement.js"
50 = "/Common/javascript/Source/clientcide/UI/IconMenu.js"
51 = "/Common/javascript/Source/clientcide/UI/StyleWriter.js"
52 = "/Common/javascript/Source/clientcide/UI/StickyWin.js"
53 = "/Common/javascript/Source/clientcide/UI/StickyWin.Modal.js"
54 = "/Common/javascript/Source/mootools-more/Interface/HtmlTable.js"
55 = "/Common/javascript/Source/uthando/Fx/Fx.MorphElement.js"
56 = "/Common/javascript/Source/uthando/FileManager/FileManager.js"
57 = "/Common/javascript/Source/uthando/FileManager/FileManager.en.js"
58 = "/Common/javascript/Source/uthando/FileManager/Additions.js"
59 = "/Common/javascript/Source/uthando/FileManager/Fx.ProgressBar.js"
60 = "/Common/javascript/Source/uthando/FileManager/Swiff.Uploader.js"
61 = "/Common/javascript/Source/uthando/FileManager/Uploader.js"
62 = "/Common/javascript/Source/uthando/FileManager/FileManager.TinyMCE.js"
63 = "/Common/javascript/Source/uthando/Layout/SlideShow.js"
64 = "/Common/javascript/Source/uthando/Layout/Tabs.js"
65 = "/Common/javascript/Source/uthando/Layout/MorphTabs.js"
66 = "/Common/javascript/Source/uthando/Layout/Pagination.js"
67 = "/Common/javascript/Source/mootools-more/Fx/Fx.Accordion.js"
68 = "/Common/javascript/Source/clientcide/Layout/MooScroller.js"


; -- END PROTECTED_MODE
; */
?>
