<?php
; /*
; -- BEGIN PROTECTED_MODE
; This files was automagically generated by ConfigMagik
; Do not edit this file by hand, use ConfigMagik instead.
; Last modified: 27 Nov 2009 23:37 40
[cache]
load = "0"
css = "/templates/papira/css/UthandoCSSCache.css"
[css]
0 = "/templates/walls/css/style.css"
[js_ini_files]

[mootools_js]

; -- END PROTECTED_MODE
; */
?>
