<h1>Modules</h1>

<table class="datatable">
    <thead>
        <tr>
            <th>Module</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->modules as $module): ?>
        <tr>
            <td><?= $this->escape($module->module); ?></td>
            <td>
                <a href="<?= $this->url(array(
                    'controller'    => 'module',
                    'action'        => 'enable',
                    'id'            => $module->id
                ), 'admin', true); ?>">
                <?php if ($module->enabled == 1): ?>
                    <img src="/images/24x24/IndicatorCircleGreenOn.png" class="Tips" title="Module Enabled" rel="Click to disable module" />
                <?php else: ?>
                     <img src="/images/24x24/IndicatorCircleRedOff.png" class="Tips" title="Module Disabled" rel="Click to enable module" />
                <?php endif; ?>
                </a>
            </td>
            <td>
                <a href="<?= $this->url(array(
                    'controller'    => 'module',
                    'action'        => 'delete',
                    'id'            => $module->id
                ), 'admin', true); ?>"><img src="/images/24x24/DeleteRed.png" class="Tips" title="Delete Module" rel="Click to delete Module" /></a>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>